name: Ansible Playbook Lint
on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.7

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Ansible Lint
        run: |
          python -m pip install --upgrade ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint --version && ansible-lint opensearch.yml
