name: Ansible Playbook Lint
on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_VERSION: 4

    steps:
      - uses: actions/checkout@v2

      - name: Run ansible-lint
        run: docker run --rm -v $(pwd):/data cytopia/ansible-lint:${{ env.ANSIBLE_VERSION }} *.yml

      #- name: Set up Python ${{ env.PYTHON_VERSION }}
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: ${{ env.PYTHON_VERSION }}

      #- name: Install Ansible Lint
      #  run: |
      #    python -m pip install --upgrade ansible ansible-lint

      #- name: Run ansible-lint
      #  run: ansible-lint --version && ansible-lint opensearch.yml
